export const GET_AUTHORS = "GET_AUTHORS";
export const GET_AUTHORS_INIT = "GET_AUTHORS_INIT";
export const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS";
export const GET_AUTHORS_FINISH = "GET_AUTHORS_FINISH";
