export const GET_AUTHORS = "GET_AUTHORS";
export const GET_AUTHORS_INIT = "GET_AUTHORS_INIT";
export const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS";
export const GET_AUTHORS_FINISH = "GET_AUTHORS_FINISH";

export const ADD_AUTHOR = "ADD_AUTHOR";
export const ADD_AUTHOR_INIT = "ADD_AUTHOR_INIT";
export const ADD_AUTHOR_SUCCESS = "ADD_AUTHOR_SUCCESS";
export const ADD_AUTHOR_FINISH = "ADD_AUTHOR_FINISH";

export const DELETE_AUTHOR = "DELETE_AUTHOR";
