export const GET_ROLES = "GET_ROLES";
export const GET_ROLES_INIT = "GET_ROLES_INIT";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_FINISH = "GET_ROLES_FINISH";

export const DELETE_ROLE = "DELETE_ROLE";
