export const GET_BOOKS = "GET_BOOKS";
export const GET_BOOKS_INIT = "GET_BOOKS_INIT";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FINISH = "GET_BOOKS_FINISH";

export const DELETE_BOOK = "DELETE_BOOK";
