export const GET_USERS = "GET_USERS";
export const GET_USERS_INIT = "GET_USERS_INIT";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FINISH = "GET_USERS_FINISH";

export const DELETE_USER = "DELETE_USER";
